# Generated by Django 2.0.7 on 2018-07-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='lang',
            new_name='language',
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(help_text='Summary of the book', max_length=300),
        ),
    ]
