# Generated by Django 2.0.7 on 2018-07-12 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180711_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='lang',
            new_name='language',
        ),
    ]
