# Generated by Django 2.0.7 on 2018-09-22 12:23

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180712_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(help_text='Who is the publisher?', max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='imprint',
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(help_text='Who is the publisher?', max_length=40, null=True, verbose_name=catalog.models.Publisher),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(help_text='Which language is the book written in?', max_length=30),
        ),
    ]
